### ISSUE TITLE
Update document.AppendExistentialDetails to test for pre-2019 EDTF unknown values

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/go-whosonfirst-spelunker#2]
https://github.com/whosonfirst/go-whosonfirst-spelunker/blob/main/document/existential.go#L25-L36

Context: https://github.com/whosonfirst/go-whosonfirst-spelunker-httpd/issues/7

**Comment by straup** [comment]
Fixed in https://github.com/whosonfirst/go-whosonfirst-spelunker/commit/346a9232284782fb906642d815e22ad689cf747c
